'use client' // This marks the file as a Client Component

import { useEffect } from 'react'
import localFont from 'next/font/local'
import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css' // Import your global styles
import { Toaster } from 'react-hot-toast' // Import the Toaster component

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export default function RootLayout({ children }) {
    useEffect(() => {
        // Dynamically import Bootstrap's JavaScript when the document is available
        if (typeof document !== 'undefined') {
            require('bootstrap/dist/js/bootstrap.bundle.min.js')
        }
    }, [])

    return (
        <html lang="en">
            <head>
                <title>Stray Finder 24</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Toaster position='top-right' /> {/* Add the Toaster here */}
                {children}
            </body>
        </html>
    )
}
